### ISSUE TITLE
Remove unnecessary data files

### ISSUE THREAD

**Issue by amy-corson** [chihacknight/ghost-buses-frontend#52]

**Comment by hkier** [comment]
I have looked at the files in the front end repository and do not see any evidence of unneeded data files.  All the files which are in the data directory are being used in the code.  There is another issue about moving these files so the code does not need to be redeployed every time the data files are updated.  BUT this is a different issue.  This issue is being close.  Unneeded files can be removed as they are found by the developer who is working on that section and with the PR for those issues if the situation arises.
